language: python
python:
  - 3.7
install:
  - pip install -q -r requirements-dev.txt
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - pipenv lock
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_sucess:
  - codecov
